version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # group everything together
      maven-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10